<script setup>
import AdminLayout from '@/Layouts/AdminLayout.vue';
import { Head, Link, router } from '@inertiajs/vue3';

const props = defineProps({ assignments: Object, routePrefix: { type: String, default: 'admin' } });
const r = (name, params) => route(`${props.routePrefix}.exam-room-assignments.${name}`, params);
const destroy = (a) => confirm('Hapus penempatan peserta?') && router.delete(r('destroy', a.id));
</script>
<template><Head title="Penempatan Peserta"/><AdminLayout><div class="py-8"><div class="mx-auto max-w-7xl px-4"><div class="mb-6 flex justify-between"><h1 class="text-2xl font-semibold">Penempatan Peserta</h1><Link :href="r('create')" class="rounded-md bg-blue-600 px-4 py-2 text-xs font-semibold uppercase text-white">Tambah Penempatan</Link></div>
<div class="overflow-hidden bg-white shadow-sm sm:rounded-lg"><div class="overflow-x-auto"><table class="min-w-full divide-y"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs uppercase text-gray-500">Jadwal</th><th class="px-6 py-3 text-left text-xs uppercase text-gray-500">Ruang</th><th class="px-6 py-3 text-left text-xs uppercase text-gray-500">Pengawas</th><th class="px-6 py-3 text-left text-xs uppercase text-gray-500">Peserta / Kuota</th><th class="px-6 py-3 text-left text-xs uppercase text-gray-500">Kapasitas Ruang</th><th class="px-6 py-3 text-left text-xs uppercase text-gray-500">Status</th><th class="px-6 py-3 text-right text-xs uppercase text-gray-500">Aksi</th></tr></thead><tbody class="divide-y"><tr v-for="a in assignments.data" :key="a.id"><td class="px-6 py-4 text-sm">{{ a.schedule?.title || '-' }}</td><td class="px-6 py-4 text-sm">{{ a.room?.name || '-' }}</td><td class="px-6 py-4 text-sm">{{ a.supervisor?.name || '-' }}</td><td class="px-6 py-4 text-sm">{{ a.participants_count }}/{{ a.max_participants }}</td><td class="px-6 py-4 text-sm">{{ a.room?.capacity || '-' }}</td><td class="px-6 py-4 text-sm">{{ a.status }}</td><td class="px-6 py-4 text-right text-sm"><Link :href="r('show', a.id)" class="text-indigo-600">Detail</Link><Link :href="r('edit', a.id)" class="ms-4 text-blue-600">Edit</Link><button class="ms-4 text-red-600" type="button" @click="destroy(a)">Hapus</button></td></tr><tr v-if="assignments.data.length===0"><td colspan="7" class="px-6 py-8 text-center text-sm text-gray-500">Belum ada penempatan.</td></tr></tbody></table></div></div></div></div></AdminLayout></template>
